chore: remove unused code
This fixes an error in CI:

```
error: struct `TestTask` is never constructed
   --> src/decider.rs:124:23
    |
124 |     pub(crate) struct TestTask(TaskOutcome);
    |                       ^^^^^^^^
    |
note: the lint level is defined here
   --> src/main.rs:2:9
    |
2   | #![deny(warnings, missing_docs)]
    |         ^^^^^^^^
    = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`

error: could not compile `retry` (bin "retry" test) due to 1 previous error
```