fix(deps): update nix flakes
Upon cloning this repository, I was met with errors compileing the tool:

```
error: package `clap_derive v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.71.1
Either upgrade to rustc 1.74 or newer, or use
cargo update -p clap_derive@4.5.4 --precise ver
where `ver` is the latest version of `clap_derive` supporting rustc 1.71.1
```

It seems that while dependabot was updateing packages, the nix flake
has not been updated in two years.

This commit was generated by running the following:

```
cd ./nix
nix flake update
cd ..
nix flake update
```

The version of `rustc` and it's related binaries changed from `1.71.1`
to `1.77.1`.